# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170905_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
